[package]
name = "cashier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash_core = { path = "../crates/ash_core" }
bincode = "1.3.3"
llvm-sys = "140"